on: [push]

jobs:
  clone_job:
    runs-on: ubuntu-latest
    name: clone a repo
    steps:
      - name: checkout test1
        uses: actions/checkout@v4
      - name: clone test2
        uses: ./
        with:
          test2_key: ${{ secrets.TEST2_KEY }}
