on: [push]

jobs:
  clone_job:
    runs-on: ubuntu-latest
    name: clone a repo
    steps:
      - name: checkout test1
        uses: actions/checkout@v4
      - name: config ssh keys
        env:
          TEST2_KEY: ${{ secrets.TEST2_KEY }}
        run: |
          eval `ssh-agent -s`
          echo "$TEST2_KEY" | tr -d '\r' | ssh-add -
          ssh-add -L
      - name: clone test2
        run: |
          git clone ssh://git@github.com/cjmakes/test2
